spring.datasource.url=jdbc:postgresql://localhost/meubanco
spring.datasource.username=meu banco
spring.datasource.password=minha senha
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=truedate